### ISSUE TITLE
Unterminated String

### ISSUE THREAD

**Issue by markkimsal** [liu-xiao-guo/youdao-cli#1]
> yd 舰队
> Traceback (most recent call last):
>   File "/snap/yd/2/bin/yd", line 7, in <module>
>     from youdao.main import main
>   File "/snap/yd/2/lib/python2.7/site-packages/youdao/main.py", line 196
>     config.set_dict_path(SNAP + "/dicts)
>                                        ^
> SyntaxError: EOL while scanning string literal

 ` config.set_dict_path(SNAP + "/dicts)`

` config.set_dict_path(SNAP + "/dicts")`

Please release a new snap of this application :D

**Comment by physchemcoder** [comment]
I was quite excited about this snap app on Ubuntu when I found it. But this simple blocker indeed makes it unusable. could you please kick off another release? Thanks.

**Comment by lxw0109** [comment]
Yes, the same request.

**Comment by sirbaT** [comment]
确实有此问题
